scrape_configs:
  - job_name: 'NHK easy api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.1.0.8:8080']
        labels:
          application: 'NHK easy api'
  - job_name: 'NHK easy task'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.1.0.6:8080']
        labels:
          application: 'NHK easy task'
